name: jaspr_bench
publish_to: none
description: Jaspr JS-Benchmarks
version: 1.0.0

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  jaspr: ^0.15.0
  js: any

dev_dependencies:
  build_runner: ^2.4.0
  build_web_compilers: ^4.0.0
  lints: ^3.0.0
