name: jaspr_bench
publish_to: none
description: Jaspr JS-Benchmarks
version: 1.0.0

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  jaspr:
    path: /Users/kilian/Documents/Work/Packages/jaspr/packages/jaspr

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
  webdev: ^2.7.10
